import { describe, it, expect, vi, afterEach } from 'vitest';
import { downloadAndInstallNodeDef } from '@/core/registry/installer';
import { InMemoryFileSystem } from '@/platform/inMemoryFileSystem';
import type { RemoteNodeDefSummary } from '@/core/registry/remoteRegistry';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const VALID_YAML = [
  'kind: NodeDef',
  'apiVersion: v1',
  'metadata:',
  '  name: kubernetes-deployment',
  '  namespace: community',
  '  version: "1.0.0"',
  '  displayName: Kubernetes Deployment',
  '  description: A K8s Deployment node',
  '  icon: Box',
  '  shape: rectangle',
  'spec:',
  '  ports: []',
].join('\n');

const INVALID_YAML = 'kind: NotANodeDef\nsome: thing';

const summary: RemoteNodeDefSummary = {
  namespace: 'community',
  name: 'kubernetes-deployment',
  version: '1.0.0',
  displayName: 'Kubernetes Deployment',
};

function mockFetchYaml(yaml: string): void {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
    ok: true,
    text: async () => yaml,
  }));
}

function mockFetchError(status: number): void {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
    ok: false,
    status,
  }));
}

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('downloadAndInstallNodeDef', () => {
  it('writes file to .archcanvas/nodedefs/{namespace}-{name}.yaml', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, 'myproject', summary);

    const expected = 'myproject/.archcanvas/nodedefs/community-kubernetes-deployment.yaml';
    const content = await fs.readFile(expected);
    expect(content).toBe(VALID_YAML);
  });

  it('updates lockfile with source: remote for installed key', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, 'myproject', summary);

    const lockContent = await fs.readFile('myproject/.archcanvas/registry.lock.yaml');
    expect(lockContent).toContain('community/kubernetes-deployment');
    expect(lockContent).toContain("source: remote");
    expect(lockContent).toContain('version: 1.0.0');
  });

  it('null guard: creates new lockfile if none exists', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();
    // No lockfile pre-seeded — installer must create one from scratch

    await expect(downloadAndInstallNodeDef(fs, 'myproject', summary)).resolves.not.toThrow();

    const lockExists = await fs.exists('myproject/.archcanvas/registry.lock.yaml');
    expect(lockExists).toBe(true);
  });

  it('preserves existing lockfile entries when adding a new one', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();

    // Pre-seed a lockfile with an existing entry
    const existingLockYaml = [
      '# Auto-generated by ArchCanvas',
      'lockfileVersion: 1',
      "resolvedAt: '2026-01-01T00:00:00.000Z'",
      'entries:',
      '  compute/service:',
      "    version: '2.0.0'",
      '    source: local',
    ].join('\n');
    fs.seed({ 'myproject/.archcanvas/registry.lock.yaml': existingLockYaml });

    await downloadAndInstallNodeDef(fs, 'myproject', summary);

    const lockContent = await fs.readFile('myproject/.archcanvas/registry.lock.yaml');
    // Both old and new entries should be present
    expect(lockContent).toContain('compute/service');
    expect(lockContent).toContain('community/kubernetes-deployment');
  });

  it('throws and writes no file for invalid YAML from registry', async () => {
    mockFetchYaml(INVALID_YAML);
    const fs = new InMemoryFileSystem();

    await expect(downloadAndInstallNodeDef(fs, 'myproject', summary)).rejects.toThrow(
      /Invalid NodeDef from registry/,
    );

    // File must NOT have been written
    const fileExists = await fs.exists(
      'myproject/.archcanvas/nodedefs/community-kubernetes-deployment.yaml',
    );
    expect(fileExists).toBe(false);
  });

  it('throws when fetch fails with HTTP error', async () => {
    mockFetchError(404);
    const fs = new InMemoryFileSystem();

    await expect(downloadAndInstallNodeDef(fs, 'myproject', summary)).rejects.toThrow(
      'Failed to fetch NodeDef YAML: 404',
    );
  });

  it('works with empty projectRoot', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, '', summary);

    const expected = '.archcanvas/nodedefs/community-kubernetes-deployment.yaml';
    const exists = await fs.exists(expected);
    expect(exists).toBe(true);
  });

  it('throws if name contains a path separator "/"', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();
    const badSummary: RemoteNodeDefSummary = { ...summary, name: 'evil/../../escape' };

    await expect(downloadAndInstallNodeDef(fs, 'myproject', badSummary)).rejects.toThrow(
      /Invalid NodeDef identifier/,
    );

    // Must not have written any file
    const exists = await fs.exists(
      'myproject/.archcanvas/nodedefs/community-evil/../../escape.yaml',
    );
    expect(exists).toBe(false);
  });

  it('throws if namespace contains a backslash "\\"', async () => {
    mockFetchYaml(VALID_YAML);
    const fs = new InMemoryFileSystem();
    const badSummary: RemoteNodeDefSummary = { ...summary, namespace: 'evil\\ns' };

    await expect(downloadAndInstallNodeDef(fs, 'myproject', badSummary)).rejects.toThrow(
      /Invalid NodeDef identifier/,
    );
  });
});
