import { describe, it, expect, vi, afterEach } from 'vitest';
import { parse } from 'yaml';
import { downloadAndInstallNodeDef } from '@/core/registry/installer';
import { InMemoryFileSystem } from '@/platform/inMemoryFileSystem';
import type { RemoteNodeDefRef } from '@/core/registry/remoteRegistry';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const VALID_BLOB = {
  kind: 'NodeDef',
  apiVersion: 'v1',
  metadata: {
    name: 'kubernetes-deployment',
    namespace: 'community',
    version: '1.0.0',
    displayName: 'Kubernetes Deployment',
    description: 'A K8s Deployment node',
    icon: 'Box',
    shape: 'rectangle',
  },
  spec: { ports: [] },
};

const INVALID_BLOB = { kind: 'NotANodeDef', some: 'thing' };

const summary: RemoteNodeDefRef = {
  namespace: 'community',
  name: 'kubernetes-deployment',
  latestVer: '1.0.0',
  displayName: 'Kubernetes Deployment',
};

// The platform's detail endpoint returns the NodeDef contents in version.blob;
// fetchNodeDefYaml serializes that locally. The mock mirrors the production
// shape so the validator path is exercised end-to-end.
function mockFetchDetail(blob: unknown): void {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
    ok: true,
    json: async () => ({
      nodedef: {
        namespace: summary.namespace,
        name: summary.name,
        latestVer: summary.latestVer,
      },
      version: {
        nodedefId: 'mock-id',
        version: summary.latestVer,
        blob,
        publishedAt: '2026-01-01T00:00:00.000Z',
      },
    }),
  }));
}

function mockFetchError(status: number): void {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
    ok: false,
    status,
  }));
}

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('downloadAndInstallNodeDef', () => {
  it('writes file to .archcanvas/nodedefs/{namespace}-{name}.yaml', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, summary);

    const expected = '.archcanvas/nodedefs/community-kubernetes-deployment.yaml';
    const content = await fs.readFile(expected);
    // Compare semantically — yaml.stringify formatting may differ from any
    // hand-written reference, but the parsed structure must match the blob.
    expect(parse(content)).toEqual(VALID_BLOB);
  });

  it('updates lockfile with source: remote for installed key', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, summary);

    const lockContent = await fs.readFile('.archcanvas/registry.lock.yaml');
    expect(lockContent).toContain('community/kubernetes-deployment');
    expect(lockContent).toContain("source: remote");
    expect(lockContent).toContain('version: 1.0.0');
  });

  it('null guard: creates new lockfile if none exists', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();
    // No lockfile pre-seeded — installer must create one from scratch

    await expect(downloadAndInstallNodeDef(fs, summary)).resolves.not.toThrow();

    const lockExists = await fs.exists('.archcanvas/registry.lock.yaml');
    expect(lockExists).toBe(true);
  });

  it('preserves existing lockfile entries when adding a new one', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();

    // Pre-seed a lockfile with an existing entry
    const existingLockYaml = [
      '# Auto-generated by ArchCanvas',
      'lockfileVersion: 1',
      "resolvedAt: '2026-01-01T00:00:00.000Z'",
      'entries:',
      '  compute/service:',
      "    version: '2.0.0'",
      '    source: local',
    ].join('\n');
    fs.seed({ '.archcanvas/registry.lock.yaml': existingLockYaml });

    await downloadAndInstallNodeDef(fs, summary);

    const lockContent = await fs.readFile('.archcanvas/registry.lock.yaml');
    // Both old and new entries should be present
    expect(lockContent).toContain('compute/service');
    expect(lockContent).toContain('community/kubernetes-deployment');
  });

  it('throws and writes no file for invalid blob from registry', async () => {
    mockFetchDetail(INVALID_BLOB);
    const fs = new InMemoryFileSystem();

    await expect(downloadAndInstallNodeDef(fs, summary)).rejects.toThrow(
      /Invalid NodeDef from registry/,
    );

    // File must NOT have been written
    const fileExists = await fs.exists(
      '.archcanvas/nodedefs/community-kubernetes-deployment.yaml',
    );
    expect(fileExists).toBe(false);
  });

  it('throws when fetch fails with HTTP error', async () => {
    mockFetchError(404);
    const fs = new InMemoryFileSystem();

    await expect(downloadAndInstallNodeDef(fs, summary)).rejects.toThrow(
      'Failed to fetch NodeDef detail: 404',
    );
  });

  it('works with empty projectRoot', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, summary);

    const expected = '.archcanvas/nodedefs/community-kubernetes-deployment.yaml';
    const exists = await fs.exists(expected);
    expect(exists).toBe(true);
  });

  it('throws if name contains a path separator "/"', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();
    const badSummary: RemoteNodeDefRef = { ...summary, name: 'evil/../../escape' };

    await expect(downloadAndInstallNodeDef(fs, badSummary)).rejects.toThrow(
      /Invalid NodeDef identifier/,
    );

    // Must not have written any file
    const exists = await fs.exists(
      '.archcanvas/nodedefs/community-evil/../../escape.yaml',
    );
    expect(exists).toBe(false);
  });

  it('throws if namespace contains a backslash "\\"', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();
    const badSummary: RemoteNodeDefRef = { ...summary, namespace: 'evil\\ns' };

    await expect(downloadAndInstallNodeDef(fs, badSummary)).rejects.toThrow(
      /Invalid NodeDef identifier/,
    );
  });

  it('writes source: remote-official to lockfile when source param is remote-official', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, summary, 'remote-official');

    const lockContent = await fs.readFile('.archcanvas/registry.lock.yaml');
    expect(lockContent).toContain('community/kubernetes-deployment');
    expect(lockContent).toContain('source: remote-official');
    expect(lockContent).toContain('version: 1.0.0');
  });

  it('writes source: remote to lockfile when no source param is given (default)', async () => {
    mockFetchDetail(VALID_BLOB);
    const fs = new InMemoryFileSystem();

    await downloadAndInstallNodeDef(fs, summary);

    const lockContent = await fs.readFile('.archcanvas/registry.lock.yaml');
    expect(lockContent).toContain('source: remote');
    expect(lockContent).not.toContain('source: remote-official');
  });
});
