import { describe, it, expect, vi } from 'vitest';
import {
  parseLockfile,
  serializeLockfile,
  generateLockfile,
  loadLockfile,
  saveLockfile,
  type LockfileData,
} from '@/core/registry/lockfile';
import type { NodeDefRegistry } from '@/core/registry/core';
import type { NodeDef } from '@/types';
import type { FileSystem } from '@/platform/fileSystem';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeNodeDef(namespace: string, name: string, version = '1.0.0'): NodeDef {
  return {
    kind: 'NodeDef',
    apiVersion: 'v1',
    metadata: {
      name,
      namespace,
      version,
      displayName: name,
      description: `A ${name} node`,
      icon: 'Box',
      shape: 'rectangle',
    },
    spec: {},
  };
}

function makeMockFs(files: Record<string, string> = {}): FileSystem {
  const store = { ...files };
  return {
    getName: () => 'mock',
    getPath: () => null,
    readFile: vi.fn(async (path: string) => {
      if (!(path in store)) throw new Error(`File not found: ${path}`);
      return store[path];
    }),
    readFileBytes: vi.fn(async (path: string) => {
      if (!(path in store)) throw new Error(`File not found: ${path}`);
      return new TextEncoder().encode(store[path]);
    }),
    stat: vi.fn(async (path: string) => {
      if (!(path in store)) {
        const err = new Error(`ENOENT: '${path}'`) as Error & { code: string };
        err.code = 'ENOENT';
        throw err;
      }
      return { type: 'file' as const, size: new TextEncoder().encode(store[path]).length, mtimeMs: 0 };
    }),
    writeFile: vi.fn(async (path: string, content: string) => {
      store[path] = content;
    }),
    listFiles: vi.fn(async () => []),
    exists: vi.fn(async (path: string) => path in store),
    mkdir: vi.fn(async () => {}),
    listEntries: vi.fn(async () => []),
    listFilesRecursive: vi.fn(async () => []),
    deleteFile: vi.fn(async () => {}),
  };
}

function validLockfileYaml(): string {
  return [
    'lockfileVersion: 1',
    "resolvedAt: '2026-04-14T12:00:00Z'",
    'entries:',
    '  data/database:',
    "    version: '1.0.0'",
    '    source: builtin',
    '  compute/service:',
    "    version: '1.0.0'",
    '    source: local',
    "    constraint: '^1.0.0'",
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('parseLockfile', () => {
  it('parses valid lockfile YAML', () => {
    const result = parseLockfile(validLockfileYaml());
    expect(result).not.toBeNull();
    expect(result!.lockfileVersion).toBe(1);
    expect(result!.entries['data/database']).toEqual({
      version: '1.0.0',
      source: 'builtin',
    });
    expect(result!.entries['compute/service']).toEqual({
      version: '1.0.0',
      source: 'local',
      constraint: '^1.0.0',
    });
  });

  it('returns null for invalid YAML', () => {
    expect(parseLockfile('{{{')).toBeNull();
  });

  it('returns null for missing required fields', () => {
    expect(parseLockfile('lockfileVersion: 1\n')).toBeNull();
  });

  it('parses lockfile with empty entries', () => {
    const yaml = [
      'lockfileVersion: 1',
      "resolvedAt: '2026-04-14T12:00:00Z'",
      'entries: {}',
    ].join('\n');
    const result = parseLockfile(yaml);
    expect(result).not.toBeNull();
    expect(Object.keys(result!.entries)).toHaveLength(0);
  });

  it('parses lockfile with unknown lockfileVersion', () => {
    const yaml = [
      'lockfileVersion: 99',
      "resolvedAt: '2026-04-14T12:00:00Z'",
      'entries: {}',
    ].join('\n');
    const result = parseLockfile(yaml);
    expect(result).not.toBeNull();
    expect(result!.lockfileVersion).toBe(99);
  });
});

describe('serializeLockfile', () => {
  it('includes header comment', () => {
    const data: LockfileData = {
      lockfileVersion: 1,
      resolvedAt: '2026-04-14T12:00:00Z',
      entries: {},
    };
    const output = serializeLockfile(data);
    expect(output).toContain('# Auto-generated by ArchCanvas');
    expect(output).toContain('# Delete this file to regenerate');
  });

  it('round-trips with parseLockfile', () => {
    const data: LockfileData = {
      lockfileVersion: 1,
      resolvedAt: '2026-04-14T12:00:00Z',
      entries: {
        'data/database': { version: '1.0.0', source: 'builtin' },
        'compute/service': { version: '2.0.0', source: 'local', constraint: '^2.0.0' },
      },
    };
    const yaml = serializeLockfile(data);
    const parsed = parseLockfile(yaml);
    expect(parsed).not.toBeNull();
    expect(parsed!.lockfileVersion).toBe(data.lockfileVersion);
    expect(parsed!.entries['data/database']).toEqual(data.entries['data/database']);
    expect(parsed!.entries['compute/service']).toEqual(data.entries['compute/service']);
  });
});

describe('generateLockfile', () => {
  it('generates entries for all registry types', () => {
    const defs = [
      makeNodeDef('data', 'database'),
      makeNodeDef('compute', 'service'),
    ];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    const result = generateLockfile(registry, new Set());
    expect(result.lockfileVersion).toBe(1);
    expect(result.resolvedAt).toBeTruthy();
    expect(result.entries['data/database']).toEqual({
      version: '1.0.0',
      source: 'builtin',
    });
    expect(result.entries['compute/service']).toEqual({
      version: '1.0.0',
      source: 'builtin',
    });
  });

  it('marks project-local sources correctly', () => {
    const defs = [
      makeNodeDef('custom', 'widget', '2.0.0'),
      makeNodeDef('data', 'database'),
    ];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    const result = generateLockfile(registry, new Set(['custom/widget']));
    expect(result.entries['custom/widget'].source).toBe('local');
    expect(result.entries['data/database'].source).toBe('builtin');
  });

  it('marks remote-installed keys with source: remote', () => {
    const defs = [
      makeNodeDef('community', 'k8s-deploy'),
      makeNodeDef('data', 'database'),
    ];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    const result = generateLockfile(
      registry,
      new Set(),
      new Set(['community/k8s-deploy']),
    );
    expect(result.entries['community/k8s-deploy'].source).toBe('remote');
    expect(result.entries['data/database'].source).toBe('builtin');
  });

  it('remote wins over projectLocal when key is in both sets', () => {
    const defs = [makeNodeDef('custom', 'widget')];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    const result = generateLockfile(
      registry,
      new Set(['custom/widget']),     // also in projectLocalKeys
      new Set(['custom/widget']),     // also in remoteInstalledKeys — should win
    );
    expect(result.entries['custom/widget'].source).toBe('remote');
  });

  it('without remoteInstalledKeys, behaviour is unchanged', () => {
    const defs = [
      makeNodeDef('custom', 'widget'),
      makeNodeDef('data', 'database'),
    ];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    // omit 3rd arg entirely
    const result = generateLockfile(registry, new Set(['custom/widget']));
    expect(result.entries['custom/widget'].source).toBe('local');
    expect(result.entries['data/database'].source).toBe('builtin');
  });

  it('marks remoteOfficialKeys with source: remote-official', () => {
    const defs = [
      makeNodeDef('compute', 'service'),
      makeNodeDef('data', 'database'),
    ];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    const result = generateLockfile(
      registry,
      new Set(),
      new Set(),
      new Set(['compute/service']),
    );
    expect(result.entries['compute/service'].source).toBe('remote-official');
    expect(result.entries['data/database'].source).toBe('builtin');
  });

  it('remoteOfficialKeys wins over remoteInstalledKeys when key is in both', () => {
    const defs = [makeNodeDef('compute', 'service')];
    const registry: NodeDefRegistry = {
      resolve: () => undefined,
      resolveVersioned: () => ({ nodeDef: undefined, versionMatch: false }),
      list: () => defs,
      search: () => [],
      listByNamespace: () => [],
    };

    const result = generateLockfile(
      registry,
      new Set(),
      new Set(['compute/service']),  // also in remoteInstalledKeys
      new Set(['compute/service']),  // also in remoteOfficialKeys — should win
    );
    expect(result.entries['compute/service'].source).toBe('remote-official');
  });
});

describe('parseLockfile with remote-official source', () => {
  it("parses 'remote-official' source correctly", () => {
    const yaml = [
      'lockfileVersion: 1',
      "resolvedAt: '2026-04-14T12:00:00Z'",
      'entries:',
      '  compute/service:',
      "    version: '1.0.0'",
      '    source: remote-official',
    ].join('\n');

    const result = parseLockfile(yaml);
    expect(result).not.toBeNull();
    expect(result!.entries['compute/service'].source).toBe('remote-official');
  });

  it("rejects an unknown source value", () => {
    const yaml = [
      'lockfileVersion: 1',
      "resolvedAt: '2026-04-14T12:00:00Z'",
      'entries:',
      '  compute/service:',
      "    version: '1.0.0'",
      '    source: unknown-source',
    ].join('\n');

    const result = parseLockfile(yaml);
    expect(result).toBeNull();
  });
});

describe('loadLockfile', () => {
  it('returns null when file does not exist', async () => {
    const fs = makeMockFs();
    const result = await loadLockfile(fs);
    expect(result).toBeNull();
  });

  it('parses valid lockfile from disk', async () => {
    const fs = makeMockFs({
      '.archcanvas/registry.lock.yaml': validLockfileYaml(),
    });
    const result = await loadLockfile(fs);
    expect(result).not.toBeNull();
    expect(result!.lockfileVersion).toBe(1);
  });

  it('returns null for corrupt file', async () => {
    const fs = makeMockFs({
      '.archcanvas/registry.lock.yaml': '{{{invalid',
    });
    const result = await loadLockfile(fs);
    expect(result).toBeNull();
  });
});

describe('saveLockfile', () => {
  it('writes to correct path', async () => {
    const fs = makeMockFs();
    const data: LockfileData = {
      lockfileVersion: 1,
      resolvedAt: '2026-04-14T12:00:00Z',
      entries: {},
    };
    await saveLockfile(fs, data);
    expect(fs.mkdir).toHaveBeenCalledWith('.archcanvas');
    expect(fs.writeFile).toHaveBeenCalledWith(
      '.archcanvas/registry.lock.yaml',
      expect.stringContaining('lockfileVersion: 1'),
    );
  });

  it('creates directory before writing', async () => {
    const fs = makeMockFs();
    const data: LockfileData = {
      lockfileVersion: 1,
      resolvedAt: '2026-04-14T12:00:00Z',
      entries: {},
    };
    await saveLockfile(fs, data);
    // mkdir called before writeFile
    const mkdirOrder = (fs.mkdir as ReturnType<typeof vi.fn>).mock.invocationCallOrder[0];
    const writeOrder = (fs.writeFile as ReturnType<typeof vi.fn>).mock.invocationCallOrder[0];
    expect(mkdirOrder).toBeLessThan(writeOrder);
  });
});
