import { z } from 'zod/v4';
import { parse, stringify } from 'yaml';
import type { FileSystem } from '@/platform/fileSystem';
import type { NodeDefRegistry } from './core';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LOCKFILE_PATH = '.archcanvas/registry.lock.yaml';
const LOCKFILE_VERSION = 1;

const LOCKFILE_HEADER = [
  '# Auto-generated by ArchCanvas — commit to git for reproducible builds',
  '# Delete this file to regenerate from current registry state',
  '',
].join('\n');

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

const LockfileEntrySchema = z.object({
  version: z.string(),
  source: z.enum(['builtin', 'local', 'remote', 'remote-official']),
  constraint: z.string().optional(),
});

const LockfileSchema = z.object({
  lockfileVersion: z.number(),
  resolvedAt: z.string(),
  entries: z.record(z.string(), LockfileEntrySchema),
});

export type LockfileEntry = z.infer<typeof LockfileEntrySchema>;
export type LockfileData = z.infer<typeof LockfileSchema>;

// ---------------------------------------------------------------------------
// Parse / Serialize
// ---------------------------------------------------------------------------

/**
 * Parse a YAML string into validated LockfileData.
 * Returns null if invalid (graceful degradation — caller should regenerate).
 */
export function parseLockfile(yamlContent: string): LockfileData | null {
  try {
    const raw = parse(yamlContent);
    const result = LockfileSchema.safeParse(raw);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

/**
 * Serialize LockfileData to a YAML string with a header comment.
 */
export function serializeLockfile(data: LockfileData): string {
  return LOCKFILE_HEADER + stringify(data);
}

// ---------------------------------------------------------------------------
// Generate
// ---------------------------------------------------------------------------

/**
 * Generate a fresh lockfile from the current registry state.
 *
 * @param registry            The fully merged NodeDef registry
 * @param projectLocalKeys    Set of type keys (namespace/name) that come from authored project-local defs
 * @param remoteInstalledKeys Optional set of type keys for community-installed defs (source:'remote')
 * @param remoteOfficialKeys  Optional set of type keys for official registry defs (source:'remote-official')
 */
export function generateLockfile(
  registry: NodeDefRegistry,
  projectLocalKeys: Set<string>,
  remoteInstalledKeys?: Set<string>,
  remoteOfficialKeys?: Set<string>,
): LockfileData {
  const entries: Record<string, LockfileEntry> = {};

  for (const def of registry.list()) {
    const key = `${def.metadata.namespace}/${def.metadata.name}`;
    let source: 'builtin' | 'local' | 'remote' | 'remote-official';
    if (remoteOfficialKeys?.has(key)) {
      source = 'remote-official';
    } else if (remoteInstalledKeys?.has(key)) {
      source = 'remote';
    } else if (projectLocalKeys.has(key)) {
      source = 'local';
    } else {
      source = 'builtin';
    }
    entries[key] = {
      version: def.metadata.version,
      source,
    };
  }

  return {
    lockfileVersion: LOCKFILE_VERSION,
    resolvedAt: new Date().toISOString(),
    entries,
  };
}

// ---------------------------------------------------------------------------
// File I/O
// ---------------------------------------------------------------------------

/**
 * Load and parse an existing lockfile from disk.
 * Returns null if the file is missing or corrupt.
 *
 * Paths are relative to the FileSystem root — the platform layer resolves them
 * against the project directory.
 */
export async function loadLockfile(
  fs: FileSystem,
): Promise<LockfileData | null> {
  try {
    const fileExists = await fs.exists(LOCKFILE_PATH);
    if (!fileExists) return null;
    const content = await fs.readFile(LOCKFILE_PATH);
    return parseLockfile(content);
  } catch {
    return null;
  }
}

/**
 * Write a lockfile to disk, creating the .archcanvas/ directory if needed.
 */
export async function saveLockfile(
  fs: FileSystem,
  data: LockfileData,
): Promise<void> {
  await fs.mkdir('.archcanvas');
  await fs.writeFile(LOCKFILE_PATH, serializeLockfile(data));
}
