import { z } from 'zod/v4';
import { parse, stringify } from 'yaml';
import type { FileSystem } from '@/platform/fileSystem';
import type { NodeDefRegistry } from './core';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LOCKFILE_PATH = '.archcanvas/registry.lock.yaml';
const LOCKFILE_VERSION = 1;

const LOCKFILE_HEADER = [
  '# Auto-generated by ArchCanvas — commit to git for reproducible builds',
  '# Delete this file to regenerate from current registry state',
  '',
].join('\n');

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

const LockfileEntrySchema = z.object({
  version: z.string(),
  source: z.enum(['builtin', 'local', 'remote']),
  constraint: z.string().optional(),
});

const LockfileSchema = z.object({
  lockfileVersion: z.number(),
  resolvedAt: z.string(),
  entries: z.record(z.string(), LockfileEntrySchema),
});

export type LockfileEntry = z.infer<typeof LockfileEntrySchema>;
export type LockfileData = z.infer<typeof LockfileSchema>;

// ---------------------------------------------------------------------------
// Parse / Serialize
// ---------------------------------------------------------------------------

/**
 * Parse a YAML string into validated LockfileData.
 * Returns null if invalid (graceful degradation — caller should regenerate).
 */
export function parseLockfile(yamlContent: string): LockfileData | null {
  try {
    const raw = parse(yamlContent);
    const result = LockfileSchema.safeParse(raw);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

/**
 * Serialize LockfileData to a YAML string with a header comment.
 */
export function serializeLockfile(data: LockfileData): string {
  return LOCKFILE_HEADER + stringify(data);
}

// ---------------------------------------------------------------------------
// Generate
// ---------------------------------------------------------------------------

/**
 * Generate a fresh lockfile from the current registry state.
 *
 * @param registry       The fully merged NodeDef registry
 * @param projectLocalKeys  Set of type keys (namespace/name) that come from project-local defs
 */
export function generateLockfile(
  registry: NodeDefRegistry,
  projectLocalKeys: Set<string>,
): LockfileData {
  const entries: Record<string, LockfileEntry> = {};

  for (const def of registry.list()) {
    const key = `${def.metadata.namespace}/${def.metadata.name}`;
    entries[key] = {
      version: def.metadata.version,
      source: projectLocalKeys.has(key) ? 'local' : 'builtin',
    };
  }

  return {
    lockfileVersion: LOCKFILE_VERSION,
    resolvedAt: new Date().toISOString(),
    entries,
  };
}

// ---------------------------------------------------------------------------
// File I/O
// ---------------------------------------------------------------------------

function lockfilePath(projectRoot: string): string {
  return projectRoot ? `${projectRoot}/${LOCKFILE_PATH}` : LOCKFILE_PATH;
}

/**
 * Load and parse an existing lockfile from disk.
 * Returns null if the file is missing or corrupt.
 */
export async function loadLockfile(
  fs: FileSystem,
  projectRoot: string,
): Promise<LockfileData | null> {
  const path = lockfilePath(projectRoot);
  try {
    const fileExists = await fs.exists(path);
    if (!fileExists) return null;
    const content = await fs.readFile(path);
    return parseLockfile(content);
  } catch {
    return null;
  }
}

/**
 * Write a lockfile to disk, creating the .archcanvas/ directory if needed.
 */
export async function saveLockfile(
  fs: FileSystem,
  projectRoot: string,
  data: LockfileData,
): Promise<void> {
  const dir = projectRoot ? `${projectRoot}/.archcanvas` : '.archcanvas';
  const path = lockfilePath(projectRoot);
  await fs.mkdir(dir);
  await fs.writeFile(path, serializeLockfile(data));
}
