/**
 * Feature #156: Save auto-generates .summary.md sidecar file.
 * Verifies that ExportApi.generateSummaryWithMermaid() combines markdown summary
 * with a fenced Mermaid diagram block.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { ExportApi } from '@/api/exportApi';
import type { ArchGraph, ArchNode, ArchEdge } from '@/types/graph';
import { generateId } from '@/utils/idGenerator';

function makeNode(overrides: Partial<ArchNode> & { type: string; displayName: string }): ArchNode {
  return {
    id: overrides.id ?? generateId(),
    type: overrides.type,
    displayName: overrides.displayName,
    args: overrides.args ?? {},
    codeRefs: overrides.codeRefs ?? [],
    notes: overrides.notes ?? [],
    properties: overrides.properties ?? {},
    position: overrides.position ?? { x: 0, y: 0, width: 200, height: 100 },
    children: overrides.children ?? [],
    refSource: overrides.refSource,
  };
}

function makeEdge(overrides: Partial<ArchEdge> & { fromNode: string; toNode: string }): ArchEdge {
  return {
    id: overrides.id ?? generateId(),
    fromNode: overrides.fromNode,
    toNode: overrides.toNode,
    type: overrides.type ?? 'sync',
    label: overrides.label,
    properties: overrides.properties ?? {},
    notes: overrides.notes ?? [],
  };
}

describe('ExportApi.generateSummaryWithMermaid() - Feature #156', () => {
  let exportApi: ExportApi;
  let graph: ArchGraph;
  let nodeA: ArchNode;
  let nodeB: ArchNode;

  beforeAll(() => {
    exportApi = new ExportApi();

    nodeA = makeNode({ id: 'node-a', type: 'compute/service', displayName: 'Auth Service' });
    nodeB = makeNode({ id: 'node-b', type: 'storage/database', displayName: 'User DB' });
    const edge: ArchEdge = makeEdge({ fromNode: 'node-a', toNode: 'node-b', type: 'sync', label: 'query' });

    graph = {
      name: 'My Test Architecture',
      description: 'A test architecture for summary generation',
      owners: ['team-alpha'],
      nodes: [nodeA, nodeB],
      edges: [edge],
    };
  });

  it('includes architecture name as heading', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('# My Test Architecture');
  });

  it('includes architecture description', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('A test architecture for summary generation');
  });

  it('includes overview table with node count', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('| Nodes  | 2 |');
  });

  it('includes overview table with edge count', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('| Edges  | 1 |');
  });

  it('includes node list in Components section', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('Auth Service');
    expect(summary).toContain('User DB');
  });

  it('includes node types', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('`compute/service`');
    expect(summary).toContain('`storage/database`');
  });

  it('includes connections section', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('`node-a` → `node-b` [sync]');
  });

  it('includes Architecture Diagram section heading', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('## Architecture Diagram');
  });

  it('includes fenced Mermaid code block', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('```mermaid');
    expect(summary).toContain('```');
  });

  it('includes Mermaid graph declaration', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('graph LR');
  });

  it('includes Mermaid node definitions', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('node_a');
    expect(summary).toContain('node_b');
    expect(summary).toContain('"Auth Service"');
    expect(summary).toContain('"User DB"');
  });

  it('includes Mermaid edge definitions', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    // Sync edge uses --> arrow
    expect(summary).toContain('node_a -->');
    expect(summary).toContain('node_b');
  });

  it('includes auto-generated notice', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    expect(summary).toContain('Auto-generated by ArchCanvas');
  });

  it('handles empty graph without errors', () => {
    const emptyGraph: ArchGraph = {
      name: 'Empty Project',
      description: '',
      owners: [],
      nodes: [],
      edges: [],
    };
    const summary = exportApi.generateSummaryWithMermaid(emptyGraph);
    expect(summary).toContain('# Empty Project');
    expect(summary).toContain('| Nodes  | 0 |');
    expect(summary).toContain('| Edges  | 0 |');
    expect(summary).toContain('```mermaid');
  });

  it('Mermaid section appears after Components section', () => {
    const summary = exportApi.generateSummaryWithMermaid(graph);
    const componentsIndex = summary.indexOf('## Components');
    const diagramIndex = summary.indexOf('## Architecture Diagram');
    expect(componentsIndex).toBeLessThan(diagramIndex);
  });
});
