/**
 * Export API - generates markdown summaries, Mermaid diagrams, PNG, and SVG exports.
 */

import type { ArchGraph, ArchNode } from '@/types/graph';
import { flattenNodes, countAllNodes } from '@/core/graph/graphQuery';
import { toPng, toSvg } from 'html-to-image';

export class ExportApi {
  constructor() {
    console.log('[ExportApi] Initialized');
  }

  /**
   * Generate a markdown summary of the architecture.
   * This is used as the auto-generated .summary.md sidecar file.
   */
  generateMarkdownSummary(graph: ArchGraph): string {
    const lines: string[] = [];
    const totalNodes = countAllNodes(graph);
    const totalEdges = graph.edges.length;

    lines.push(`# ${graph.name}`);
    lines.push('');
    if (graph.description) {
      lines.push(graph.description);
      lines.push('');
    }
    lines.push(`> Auto-generated by ArchCanvas`);
    lines.push('');
    lines.push('## Overview');
    lines.push('');
    lines.push(`| Metric | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Nodes  | ${totalNodes} |`);
    lines.push(`| Edges  | ${totalEdges} |`);
    lines.push(`| Owners | ${graph.owners.length} |`);
    lines.push('');

    if (graph.owners.length > 0) {
      lines.push('## Owners');
      lines.push('');
      for (const owner of graph.owners) {
        lines.push(`- ${owner}`);
      }
      lines.push('');
    }

    if (graph.nodes.length > 0) {
      lines.push('## Components');
      lines.push('');
      for (const node of graph.nodes) {
        this.renderNodeMarkdown(node, lines, 0);
      }
    }

    if (graph.edges.length > 0) {
      lines.push('## Connections');
      lines.push('');
      for (const edge of graph.edges) {
        const label = edge.label ? ` — "${edge.label}"` : '';
        lines.push(
          `- \`${edge.fromNode}\` → \`${edge.toNode}\` [${edge.type}]${label}`,
        );
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Generate the full .summary.md sidecar content, combining
   * the markdown summary with a fenced Mermaid diagram block.
   */
  generateSummaryWithMermaid(graph: ArchGraph): string {
    const summary = this.generateMarkdownSummary(graph);
    const mermaid = this.generateMermaid(graph);

    const mermaidSection = [
      '## Architecture Diagram',
      '',
      '```mermaid',
      mermaid,
      '```',
      '',
    ].join('\n');

    return summary + mermaidSection;
  }

  /**
   * Generate a Mermaid diagram representation of the architecture.
   */
  generateMermaid(graph: ArchGraph): string {
    const lines: string[] = [];
    lines.push('graph LR');

    const allNodes = flattenNodes(graph.nodes);

    for (const node of allNodes) {
      const shape = this.getMermaidShape(node.type);
      const safeId = this.sanitizeMermaidId(node.id);
      const safeName = node.displayName.replace(/"/g, '#quot;');
      lines.push(`    ${safeId}${shape.open}"${safeName}"${shape.close}`);
    }

    for (const edge of graph.edges) {
      const fromId = this.sanitizeMermaidId(edge.fromNode);
      const toId = this.sanitizeMermaidId(edge.toNode);
      const arrow = this.getMermaidArrow(edge.type);
      const label = edge.label ? `|"${edge.label}"|` : '';
      lines.push(`    ${fromId} ${arrow}${label} ${toId}`);
    }

    return lines.join('\n');
  }

  /**
   * Export the canvas to a PNG image and trigger a download.
   * Captures the React Flow viewport element from the DOM.
   *
   * @param fileName - Base name for the exported file (without extension)
   * @returns true if export succeeded
   */
  async exportToPng(fileName: string = 'architecture'): Promise<boolean> {
    const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null;
    if (!viewport) {
      console.error('[ExportApi] Cannot find React Flow viewport element for PNG export');
      return false;
    }

    try {
      const dataUrl = await toPng(viewport, {
        backgroundColor: '#f9fafb', // gray-50 to match canvas background
        pixelRatio: 2, // High-res export
        filter: (node: HTMLElement) => {
          // Filter out UI controls that shouldn't be in the export
          const className = node.className;
          if (typeof className === 'string') {
            if (className.includes('react-flow__minimap')) return false;
            if (className.includes('react-flow__controls')) return false;
            if (className.includes('react-flow__panel')) return false;
          }
          return true;
        },
      });

      // Trigger download
      const baseName = fileName.replace(/\.archc$/, '').replace(/\.png$/, '');
      const link = document.createElement('a');
      link.download = `${baseName}.png`;
      link.href = dataUrl;
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      console.log(`[ExportApi] PNG exported: ${baseName}.png`);
      return true;
    } catch (err) {
      console.error('[ExportApi] PNG export failed:', err);
      return false;
    }
  }

  /**
   * Export the canvas to an SVG vector image and trigger a download.
   * Captures the React Flow viewport element from the DOM.
   *
   * @param fileName - Base name for the exported file (without extension)
   * @returns true if export succeeded
   */
  async exportToSvg(fileName: string = 'architecture'): Promise<boolean> {
    const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null;
    if (!viewport) {
      console.error('[ExportApi] Cannot find React Flow viewport element for SVG export');
      return false;
    }

    try {
      const dataUrl = await toSvg(viewport, {
        backgroundColor: '#f9fafb', // gray-50 to match canvas background
        filter: (node: HTMLElement) => {
          // Filter out UI controls that shouldn't be in the export
          const className = node.className;
          if (typeof className === 'string') {
            if (className.includes('react-flow__minimap')) return false;
            if (className.includes('react-flow__controls')) return false;
            if (className.includes('react-flow__panel')) return false;
          }
          return true;
        },
      });

      // Convert data URL to SVG text for clean download
      const baseName = fileName.replace(/\.archc$/, '').replace(/\.svg$/, '');

      // Decode the data URL to get raw SVG content
      const svgContent = decodeURIComponent(dataUrl.split(',')[1] || '');

      const blob = new Blob([svgContent], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.download = `${baseName}.svg`;
      link.href = url;
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      console.log(`[ExportApi] SVG exported: ${baseName}.svg`);
      return true;
    } catch (err) {
      console.error('[ExportApi] SVG export failed:', err);
      return false;
    }
  }

  // ============================================================
  // Private helpers
  // ============================================================

  private renderNodeMarkdown(
    node: ArchNode,
    lines: string[],
    depth: number,
  ): void {
    const indent = '  '.repeat(depth);
    const heading = '#'.repeat(Math.min(depth + 3, 6));
    lines.push(`${indent}${heading} ${node.displayName}`);
    lines.push('');
    lines.push(`${indent}- **Type:** \`${node.type}\``);

    if (Object.keys(node.args).length > 0) {
      for (const [key, value] of Object.entries(node.args)) {
        lines.push(`${indent}- **${key}:** ${value}`);
      }
    }

    if (node.notes.length > 0) {
      lines.push(`${indent}- **Notes:** ${node.notes.length}`);
    }

    if (node.codeRefs.length > 0) {
      lines.push(`${indent}- **Code refs:** ${node.codeRefs.map((cr) => `\`${cr.path}\``).join(', ')}`);
    }

    lines.push('');

    for (const child of node.children) {
      this.renderNodeMarkdown(child, lines, depth + 1);
    }
  }

  private getMermaidShape(type: string): { open: string; close: string } {
    const namespace = type.split('/')[0];
    const name = type.split('/')[1];

    // Database: cylinder shape
    if (name === 'database' || name === 'cache') {
      return { open: '[(', close: ')]' };
    }
    // Queue: stadium/rounded
    if (name === 'message-queue' || name === 'event-bus') {
      return { open: '([', close: '])' };
    }
    // Gateway: hexagon
    if (name === 'api-gateway' || name === 'load-balancer') {
      return { open: '{{', close: '}}' };
    }
    // Default: rectangle
    if (namespace === 'compute') {
      return { open: '[', close: ']' };
    }
    // Observability: rounded rectangle
    if (namespace === 'observability') {
      return { open: '(', close: ')' };
    }
    return { open: '[', close: ']' };
  }

  private getMermaidArrow(type: string): string {
    switch (type) {
      case 'sync':
        return '-->';
      case 'async':
        return '-.->';
      case 'data-flow':
        return '==>';
      default:
        return '-->';
    }
  }

  private sanitizeMermaidId(id: string): string {
    // Replace characters that are not valid in Mermaid node IDs
    return id.replace(/[^a-zA-Z0-9_]/g, '_');
  }
}
