/**
 * Export API - generates markdown summaries, Mermaid diagrams, PNG, and SVG exports.
 *
 * Generation methods (pure, no side-effects):
 *   generateMarkdownSummary, generateSummaryWithMermaid, generateMermaid
 *
 * Export methods (trigger download or native share):
 *   exportToPng, exportToSvg, exportToMarkdown, exportToMermaid
 */

import type { ArchGraph, ArchNode } from '@/types/graph';
import { flattenNodes, countAllNodes } from '@/core/graph/graphQuery';
import { toPng, toSvg } from 'html-to-image';
import { isNative } from '@/core/platform/platformBridge';
import { getFileSystemAdapter } from '@/core/platform/fileSystemAdapter';

// ============================================================
// Shared helpers
// ============================================================

/**
 * Filter function for html-to-image: removes React Flow UI controls
 * (minimap, controls panel) from exported images.
 */
function viewportExportFilter(node: HTMLElement): boolean {
  const className = node.className;
  if (typeof className === 'string') {
    if (className.includes('react-flow__minimap')) return false;
    if (className.includes('react-flow__controls')) return false;
    if (className.includes('react-flow__panel')) return false;
  }
  return true;
}

/**
 * Download text or binary content as a file via the browser or native share sheet.
 * Consolidates the duplicated download logic used by markdown, mermaid, and SVG exports.
 */
async function downloadOrShare(
  content: string | Uint8Array,
  fileName: string,
  mimeType: string,
): Promise<void> {
  if (isNative()) {
    const adapter = await getFileSystemAdapter();
    await adapter.shareFile(content, fileName, mimeType);
  } else {
    const blob =
      content instanceof Uint8Array
        ? new Blob([content], { type: mimeType })
        : new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = fileName;
    link.href = url;
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

/**
 * Get the React Flow viewport element from the DOM.
 * Returns null with a console error if not found.
 */
function getViewportElement(exportType: string): HTMLElement | null {
  const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null;
  if (!viewport) {
    console.error(`[ExportApi] Cannot find React Flow viewport element for ${exportType} export`);
  }
  return viewport;
}

/**
 * Strip known file extensions from a base name to avoid double extensions.
 */
function cleanBaseName(fileName: string, ...extensions: string[]): string {
  let name = fileName;
  for (const ext of extensions) {
    name = name.replace(new RegExp(`\\.${ext.replace('.', '')}$`), '');
  }
  return name;
}

/**
 * ExportApi handles exporting architectures to various formats.
 *
 * **Generation methods** (pure, no side-effects):
 * - {@link ExportApi.generateMarkdownSummary} - Markdown overview
 * - {@link ExportApi.generateSummaryWithMermaid} - Markdown + Mermaid diagram
 * - {@link ExportApi.generateMermaid} - Standalone Mermaid diagram
 *
 * **Export methods** (trigger file download or native share):
 * - {@link ExportApi.exportToPng} / {@link ExportApi.exportToSvg} - Image exports
 * - {@link ExportApi.exportToMarkdown} / {@link ExportApi.exportToMermaid} - Text exports
 *
 * @example
 * ```ts
 * const exportApi = new ExportApi();
 * const markdown = exportApi.generateMarkdownSummary(graph);
 * await exportApi.exportToPng('my-architecture');
 * ```
 */
export class ExportApi {
  // ============================================================
  // Generation Methods (pure, no side-effects)
  // ============================================================

  /**
   * Generate a markdown summary of the architecture.
   * This is used as the auto-generated .summary.md sidecar file.
   *
   * @param graph - The architecture graph to summarize
   * @returns Markdown string with overview table, owners, components, and connections
   */
  generateMarkdownSummary(graph: ArchGraph): string {
    const lines: string[] = [];
    const totalNodes = countAllNodes(graph);
    const totalEdges = graph.edges.length;

    lines.push(`# ${graph.name}`);
    lines.push('');
    if (graph.description) {
      lines.push(graph.description);
      lines.push('');
    }
    lines.push(`> Auto-generated by ArchCanvas`);
    lines.push('');
    lines.push('## Overview');
    lines.push('');
    lines.push(`| Metric | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Nodes  | ${totalNodes} |`);
    lines.push(`| Edges  | ${totalEdges} |`);
    lines.push(`| Owners | ${graph.owners.length} |`);
    lines.push('');

    if (graph.owners.length > 0) {
      lines.push('## Owners');
      lines.push('');
      for (const owner of graph.owners) {
        lines.push(`- ${owner}`);
      }
      lines.push('');
    }

    if (graph.nodes.length > 0) {
      lines.push('## Components');
      lines.push('');
      for (const node of graph.nodes) {
        this.renderNodeMarkdown(node, lines, 0);
      }
    }

    if (graph.edges.length > 0) {
      lines.push('## Connections');
      lines.push('');
      for (const edge of graph.edges) {
        const label = edge.label ? ` — "${edge.label}"` : '';
        lines.push(`- \`${edge.fromNode}\` → \`${edge.toNode}\` [${edge.type}]${label}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Generate the full .summary.md sidecar content, combining
   * the markdown summary with a fenced Mermaid diagram block.
   *
   * @param graph - The architecture graph to export
   * @returns Complete markdown string with summary + Mermaid diagram section
   */
  generateSummaryWithMermaid(graph: ArchGraph): string {
    const summary = this.generateMarkdownSummary(graph);
    const mermaid = this.generateMermaid(graph);

    const mermaidSection = ['## Architecture Diagram', '', '```mermaid', mermaid, '```', ''].join(
      '\n',
    );

    return summary + mermaidSection;
  }

  /**
   * Generate a Mermaid diagram representation of the architecture.
   * Node shapes are mapped from node types (database=cylinder, queue=stadium, etc.).
   *
   * @param graph - The architecture graph to diagram
   * @returns Mermaid `graph LR` diagram string
   */
  generateMermaid(graph: ArchGraph): string {
    const lines: string[] = [];
    lines.push('graph LR');

    const allNodes = flattenNodes(graph.nodes);

    for (const node of allNodes) {
      const shape = this.getMermaidShape(node.type);
      const safeId = this.sanitizeMermaidId(node.id);
      const safeName = node.displayName.replace(/"/g, '#quot;');
      lines.push(`    ${safeId}${shape.open}"${safeName}"${shape.close}`);
    }

    for (const edge of graph.edges) {
      const fromId = this.sanitizeMermaidId(edge.fromNode);
      const toId = this.sanitizeMermaidId(edge.toNode);
      const arrow = this.getMermaidArrow(edge.type);
      const label = edge.label ? `|"${edge.label}"|` : '';
      lines.push(`    ${fromId} ${arrow}${label} ${toId}`);
    }

    return lines.join('\n');
  }

  // ============================================================
  // Export Methods (trigger download or native share)
  // ============================================================

  /**
   * Export the canvas to a PNG image and trigger a download.
   * Captures the React Flow viewport element from the DOM.
   *
   * @param fileName - Base name for the exported file (without extension)
   * @returns true if export succeeded
   */
  async exportToPng(fileName: string = 'architecture'): Promise<boolean> {
    const viewport = getViewportElement('PNG');
    if (!viewport) return false;

    try {
      const dataUrl = await toPng(viewport, {
        backgroundColor: '#f9fafb',
        pixelRatio: 2,
        filter: viewportExportFilter,
      });

      const baseName = cleanBaseName(fileName, 'archc', 'png');

      if (isNative()) {
        const base64Data = dataUrl.split(',')[1] || '';
        const binaryStr = atob(base64Data);
        const bytes = new Uint8Array(binaryStr.length);
        for (let i = 0; i < binaryStr.length; i++) {
          bytes[i] = binaryStr.charCodeAt(i);
        }
        await downloadOrShare(bytes, `${baseName}.png`, 'image/png');
      } else {
        // PNG uses data URL directly (no blob needed)
        const link = document.createElement('a');
        link.download = `${baseName}.png`;
        link.href = dataUrl;
        link.style.display = 'none';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }

      return true;
    } catch (err) {
      console.error('[ExportApi] PNG export failed:', err);
      return false;
    }
  }

  /**
   * Export the canvas to an SVG vector image and trigger a download.
   * Captures the React Flow viewport element from the DOM.
   *
   * @param fileName - Base name for the exported file (without extension)
   * @returns true if export succeeded
   */
  async exportToSvg(fileName: string = 'architecture'): Promise<boolean> {
    const viewport = getViewportElement('SVG');
    if (!viewport) return false;

    try {
      const dataUrl = await toSvg(viewport, {
        backgroundColor: '#f9fafb',
        filter: viewportExportFilter,
      });

      const baseName = cleanBaseName(fileName, 'archc', 'svg');
      const svgContent = decodeURIComponent(dataUrl.split(',')[1] || '');
      await downloadOrShare(svgContent, `${baseName}.svg`, 'image/svg+xml');

      return true;
    } catch (err) {
      console.error('[ExportApi] SVG export failed:', err);
      return false;
    }
  }

  /**
   * Export the architecture as a markdown summary file and trigger a download
   * (web) or present the native share sheet (iOS).
   *
   * @param graph - The architecture graph to export
   * @param fileName - Base name for the exported file (without extension)
   * @returns true if export succeeded
   */
  async exportToMarkdown(graph: ArchGraph, fileName: string = 'architecture'): Promise<boolean> {
    try {
      const content = this.generateSummaryWithMermaid(graph);
      const baseName = cleanBaseName(fileName, 'archc', 'md');
      await downloadOrShare(content, `${baseName}.md`, 'text/markdown');
      return true;
    } catch (err) {
      console.error('[ExportApi] Markdown export failed:', err);
      return false;
    }
  }

  /**
   * Export the architecture as a Mermaid diagram file (.mmd) and trigger a
   * download (web) or present the native share sheet (iOS).
   *
   * @param graph - The architecture graph to export
   * @param fileName - Base name for the exported file (without extension)
   * @returns true if export succeeded
   */
  async exportToMermaid(graph: ArchGraph, fileName: string = 'architecture'): Promise<boolean> {
    try {
      const content = this.generateMermaid(graph);
      const baseName = cleanBaseName(fileName, 'archc', 'mmd');
      await downloadOrShare(content, `${baseName}.mmd`, 'text/plain');
      return true;
    } catch (err) {
      console.error('[ExportApi] Mermaid export failed:', err);
      return false;
    }
  }

  // ============================================================
  // Private helpers
  // ============================================================

  private renderNodeMarkdown(node: ArchNode, lines: string[], depth: number): void {
    const indent = '  '.repeat(depth);
    const heading = '#'.repeat(Math.min(depth + 3, 6));
    lines.push(`${indent}${heading} ${node.displayName}`);
    lines.push('');
    lines.push(`${indent}- **Type:** \`${node.type}\``);

    if (Object.keys(node.args).length > 0) {
      for (const [key, value] of Object.entries(node.args)) {
        lines.push(`${indent}- **${key}:** ${value}`);
      }
    }

    if (node.notes.length > 0) {
      lines.push(`${indent}- **Notes:** ${node.notes.length}`);
    }

    if (node.codeRefs.length > 0) {
      lines.push(
        `${indent}- **Code refs:** ${node.codeRefs.map((cr) => `\`${cr.path}\``).join(', ')}`,
      );
    }

    lines.push('');

    for (const child of node.children) {
      this.renderNodeMarkdown(child, lines, depth + 1);
    }
  }

  private getMermaidShape(type: string): { open: string; close: string } {
    const namespace = type.split('/')[0];
    const name = type.split('/')[1];

    // Database: cylinder shape
    if (name === 'database' || name === 'cache') {
      return { open: '[(', close: ')]' };
    }
    // Queue: stadium/rounded
    if (name === 'message-queue' || name === 'event-bus') {
      return { open: '([', close: '])' };
    }
    // Gateway: hexagon
    if (name === 'api-gateway' || name === 'load-balancer') {
      return { open: '{{', close: '}}' };
    }
    // Default: rectangle
    if (namespace === 'compute') {
      return { open: '[', close: ']' };
    }
    // Observability: rounded rectangle
    if (namespace === 'observability') {
      return { open: '(', close: ')' };
    }
    return { open: '[', close: ']' };
  }

  private getMermaidArrow(type: string): string {
    switch (type) {
      case 'sync':
        return '-->';
      case 'async':
        return '-.->';
      case 'data-flow':
        return '==>';
      default:
        return '-->';
    }
  }

  private sanitizeMermaidId(id: string): string {
    return id.replace(/[^a-zA-Z0-9_]/g, '_');
  }
}
