#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────
# build-release-ios.sh - Build ArchCanvas for iOS distribution
# ────────────────────────────────────────────────────────────
#
# This script prepares the ArchCanvas iOS app for distribution
# (TestFlight / App Store). It builds the web app in production
# mode, syncs to the Capacitor iOS project, and validates the
# build is ready for Xcode Archive.
#
# Usage:
#   ./scripts/build-release-ios.sh          # Build + validate
#   ./scripts/build-release-ios.sh --open   # Build + open in Xcode
#
# After running this script, open Xcode and use:
#   Product > Archive to create an .xcarchive for distribution.
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   ArchCanvas iOS Release Build           ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

# ─── Step 1: Check prerequisites ──────────────────────────
echo -e "${YELLOW}[1/6] Checking prerequisites...${NC}"

if ! command -v node &> /dev/null; then
  echo -e "${RED}  ✗ Node.js not found${NC}"
  exit 1
fi
echo -e "${GREEN}  ✓${NC} Node.js $(node -v)"

if ! command -v npx &> /dev/null; then
  echo -e "${RED}  ✗ npx not found${NC}"
  exit 1
fi
echo -e "${GREEN}  ✓${NC} npx available"

if [ ! -d "ios" ]; then
  echo -e "${RED}  ✗ ios/ directory not found. Run 'npx cap add ios' first.${NC}"
  exit 1
fi
echo -e "${GREEN}  ✓${NC} iOS platform detected"

# ─── Step 2: Install dependencies ─────────────────────────
echo ""
echo -e "${YELLOW}[2/6] Installing dependencies...${NC}"
npm ci --silent 2>/dev/null || npm install --silent
echo -e "${GREEN}  ✓${NC} Dependencies installed"

# ─── Step 3: Build web app (production) ───────────────────
echo ""
echo -e "${YELLOW}[3/6] Building web app (production mode)...${NC}"
npx tsc -b
npx vite build
echo -e "${GREEN}  ✓${NC} Web app built to dist/"

# ─── Step 4: Validate no dev server dependency ────────────
echo ""
echo -e "${YELLOW}[4/6] Validating release configuration...${NC}"

# Ensure CAPACITOR_DEV is NOT set
if [ "${CAPACITOR_DEV:-}" = "true" ]; then
  echo -e "${RED}  ✗ CAPACITOR_DEV=true is set! Unset it for release builds.${NC}"
  exit 1
fi
echo -e "${GREEN}  ✓${NC} CAPACITOR_DEV not set (production mode)"

# Build the capacitor config and check it doesn't have dev server URL
npx cap sync ios 2>/dev/null

# Verify the generated config doesn't include a server URL
GENERATED_CONFIG="ios/App/App/capacitor.config.json"
if [ -f "$GENERATED_CONFIG" ]; then
  if grep -q '"url"' "$GENERATED_CONFIG"; then
    echo -e "${RED}  ✗ capacitor.config.json contains server URL! Remove CAPACITOR_DEV.${NC}"
    exit 1
  fi
  echo -e "${GREEN}  ✓${NC} No dev server URL in capacitor.config.json"
else
  echo -e "${YELLOW}  ! capacitor.config.json not found (will be generated by cap sync)${NC}"
fi

# ─── Step 5: Sync to iOS ─────────────────────────────────
echo ""
echo -e "${YELLOW}[5/6] Syncing web assets to iOS project...${NC}"
npx cap sync ios
echo -e "${GREEN}  ✓${NC} iOS project synced with latest web build"

# ─── Step 6: Validate iOS project ────────────────────────
echo ""
echo -e "${YELLOW}[6/6] Validating iOS project configuration...${NC}"

PBXPROJ="ios/App/App.xcodeproj/project.pbxproj"
if [ -f "$PBXPROJ" ]; then
  # Check for automatic signing
  if grep -q 'CODE_SIGN_STYLE = Automatic' "$PBXPROJ"; then
    echo -e "${GREEN}  ✓${NC} Automatic code signing enabled"
  else
    echo -e "${YELLOW}  ! Manual code signing detected — ensure provisioning profiles are configured${NC}"
  fi

  # Check deployment target
  if grep -q 'IPHONEOS_DEPLOYMENT_TARGET = 16.0' "$PBXPROJ"; then
    echo -e "${GREEN}  ✓${NC} iOS deployment target: 16.0"
  fi

  # Check bundle identifier
  if grep -q 'PRODUCT_BUNDLE_IDENTIFIER = com.archcanvas.app' "$PBXPROJ"; then
    echo -e "${GREEN}  ✓${NC} Bundle ID: com.archcanvas.app"
  fi

  # Check Release optimization
  if grep -q 'SWIFT_COMPILATION_MODE = wholemodule' "$PBXPROJ"; then
    echo -e "${GREEN}  ✓${NC} Swift whole-module optimization enabled (Release)"
  fi

  # Check product validation
  if grep -q 'VALIDATE_PRODUCT = YES' "$PBXPROJ"; then
    echo -e "${GREEN}  ✓${NC} Product validation enabled (Release)"
  fi
fi

# Verify dist/ contains expected files
if [ -f "ios/App/App/public/index.html" ]; then
  echo -e "${GREEN}  ✓${NC} Web assets present in ios/App/App/public/"
else
  echo -e "${RED}  ✗ Web assets missing from ios/App/App/public/${NC}"
  exit 1
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Release build ready!                    ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "Next steps:"
echo -e "  1. Open Xcode:  ${BLUE}npm run cap:open:ios${NC}"
echo -e "  2. Select the ${YELLOW}App${NC} scheme and ${YELLOW}Any iOS Device${NC} target"
echo -e "  3. Menu: ${YELLOW}Product > Archive${NC}"
echo -e "  4. In Organizer: ${YELLOW}Distribute App > App Store Connect${NC}"
echo ""
echo -e "For TestFlight: Select 'Upload' in the distribution dialog."
echo -e "For Ad Hoc:    Select 'Ad Hoc' distribution method."
echo ""

# Optionally open Xcode
if [ "${1:-}" = "--open" ]; then
  echo -e "${YELLOW}Opening Xcode...${NC}"
  npx cap open ios
fi
